/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-1",
    "aws_cognito_identity_pool_id": "ap-southeast-1:f9c9842a-e8ea-472c-9dc9-780d7a91dfff",
    "aws_cognito_region": "ap-southeast-1",
    "aws_user_pools_id": "ap-southeast-1_PhPB8zWzX",
    "aws_user_pools_web_client_id": "4espknla5sdu6l7f7a24qv8anb",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://k566th5hljeibfpuryujjktaxu.appsync-api.ap-southeast-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-southeast-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-ufw4qtnknbffnivctc235c67k4"
};


export default awsmobile;
